# Testing Sparse Auto Encoder (SAE)

In [5]:
# imports
import tensorflow as tf
import keras
from keras import layers
import numpy as np
import Bio
import transformers
from objects.autoencoder import SparseAutoEncoder

In [6]:
# create dataset from random tensors to test
SAE_name = 'autoencoder_test'
embed_length = 2048
ef = 4

print("=== Generating Test Data ===")
fake_embeddings = tf.random.uniform(shape=[1000, embed_length])
fake_dataset = tf.data.Dataset.from_tensor_slices((fake_embeddings, fake_embeddings)).batch(100)

print("=== Initializing Model ===")
# initialize the optimizer
optimizer = keras.optimizers.Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.98,
                                     epsilon=1e-9)

# initialize the loss function
loss = keras.losses.MeanSquaredError()

# initialize the metrics
metrics = [
    keras.metrics.MeanSquaredError(),
    keras.metrics.KLDivergence(),
]

# compile the model
autoencoder = SparseAutoEncoder(encoding_size=embed_length, expansion_factor=ef)
autoencoder.compile(optimizer=optimizer, loss=loss, metrics=metrics)

print(autoencoder.summary())

tb_callback = keras.callbacks.TensorBoard(log_dir=f'./logs/{SAE_name}', histogram_freq=5)
early_stopping = keras.callbacks.EarlyStopping(
    monitor='mean_squared_error',
    min_delta=0.001,
    patience=10, 
    restore_best_weights=True
    )

print("=== Training Model ===")
history = autoencoder.fit(fake_dataset, epochs=100, callbacks=[tb_callback, early_stopping])
print("=== Saving Model ===")
path = f'./models/{SAE_name}.keras'
#autoencoder.save(f'./models/{SAE_name}.keras')
keras.models.save_model(autoencoder, path)
print(f"Model saved to: {path}")
print(autoencoder.summary())

=== Generating Test Data ===
=== Initializing Model ===


Model: "sparse_auto_encoder_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

None
=== Training Model ===
Epoch 1/100


/home/ek224/anaconda3/envs/hsg/lib/python3.12/site-packages/keras/src/optimizers/base_optimizer.py:731: UserWarning: Gradients do not exist for variables ['variable_1'] when minimizing the loss. If using `model.compile()`, did you forget to provide a `loss` argument?
  warnings.warn(
I0000 00:00:1731516389.361528   24195 service.cc:148] XLA service 0x730844027760 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
I0000 00:00:1731516389.361556   24195 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 4070 Laptop GPU, Compute Capability 8.9
2024-11-13 10:46:29.375201: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1731516389.429279   24195 cuda_dnn.cc:529] Loaded cuDNN version 90300
2024-11-13 10:46:29.457256: W external/local_xla/xla/service/gpu/nvptx_compiler.cc:930] The NVIDIA driver's CUDA version is 12.2 which is

 6/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 2484.0159 - mean_squared_error: 0.3007

I0000 00:00:1731516391.251567   24195 device_compiler.h:188] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


10/10 ━━━━━━━━━━━━━━━━━━━━ 5s 250ms/step - loss: 2291.2083 - mean_squared_error: 0.3098
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1635.6117 - mean_squared_error: 0.3218
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 1324.4279 - mean_squared_error: 0.3120
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 1076.6309 - mean_squared_error: 0.3009
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 874.4009 - mean_squared_error: 0.2798
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 213ms/step - loss: 733.0886 - mean_squared_error: 0.2563
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 613.0953 - mean_squared_error: 0.2481
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 498.2536 - mean_squared_error: 0.2382
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 393.0520 - mean_squared_error: 0.2292
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 316.7409 - mean_squared_error: 0.1987
Epoch 11/100
10/10 ━━━━━━

Model: "sparse_auto_encoder_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_1 (InputLayer)      │ (None, 2048)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8192)           │    16,785,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 2048)           │    16,779,264 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,700,162 (384.14 MB)

 Trainable params: 33,566,720 (128.05 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 67,133,442 (256.09 MB)

None


In [7]:
feat_weights = np.array(autoencoder.weights[2])
print(f"maximum: {max(feat_weights)}")
print(f"minimum: {min(feat_weights)}")

maximum: -0.020104948431253433
minimum: -0.07123883813619614


/tmp/ipykernel_24086/1965811903.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  feat_weights = np.array(autoencoder.weights[2])


In [8]:
autoencoder.predict_on_batch(fake_embeddings[:100])

(array([[0.4283616 , 0.43124968, 0.45078814, ..., 0.43417   , 0.44790804,
         0.42558742],
        [0.41661012, 0.41918635, 0.4385472 , ..., 0.42156237, 0.43539724,
         0.4140743 ],
        [0.4105338 , 0.41315818, 0.43205646, ..., 0.41624302, 0.42956   ,
         0.4086008 ],
        ...,
        [0.4143285 , 0.41589695, 0.43441617, ..., 0.4187495 , 0.43156165,
         0.41136006],
        [0.41117036, 0.41273296, 0.43216896, ..., 0.41595316, 0.42960724,
         0.4087919 ],
        [0.4148137 , 0.41664344, 0.4359316 , ..., 0.42061287, 0.43215412,
         0.41211236]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32))

In [12]:
reconstructed_outputs, feature_outputs = autoencoder.predict_on_batch(fake_embeddings[:100])

In [13]:
reconstructed_outputs

array([[0.4283616 , 0.43124968, 0.45078814, ..., 0.43417   , 0.44790804,
        0.42558742],
       [0.41661012, 0.41918635, 0.4385472 , ..., 0.42156237, 0.43539724,
        0.4140743 ],
       [0.4105338 , 0.41315818, 0.43205646, ..., 0.41624302, 0.42956   ,
        0.4086008 ],
       ...,
       [0.4143285 , 0.41589695, 0.43441617, ..., 0.4187495 , 0.43156165,
        0.41136006],
       [0.41117036, 0.41273296, 0.43216896, ..., 0.41595316, 0.42960724,
        0.4087919 ],
       [0.4148137 , 0.41664344, 0.4359316 , ..., 0.42061287, 0.43215412,
        0.41211236]], dtype=float32)

In [14]:
feature_outputs

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [21]:
feature_outputs[0].sort()
print(feature_outputs[0][-20:])

[0.10962497 0.11038779 0.11063935 0.11066315 0.11101678 0.11137862
 0.11141063 0.11164887 0.11192642 0.11222458 0.11243407 0.11310472
 0.11502676 0.11547226 0.11565316 0.11929677 0.11941059 0.11945873
 0.12256689 0.12258448]
